### ISSUE TITLE
Add a preview for markdown content in submissions

### ISSUE THREAD

**Issue by m0rphism** [beerendlauwers/HaskAnything#29]
I think it would be convenient to display a rendered version of the markdown content before a submission via the website is performed. This would make it easier to improve the layout and detect syntax errors in the layout.

**Comment by beerendlauwers** [comment]
We're currently using Pandoc, which has been ported to JavaScript with GHCJS before. However, that might be a very heavy dependency (around 2.2MB last I checked). Perhaps we should use a simpler JavaScript-based Markdown renderer? Open to suggestions :)

**Comment by m0rphism** [comment]
That seems a bit heavy indeed :)

If people are contributing from mobile devices, something smaller would probably be good.

Unfortunately, I have almost no experience with web development, but here are two projects I've found multiple suggestions for:
- [marked](https://github.com/chjj/marked/blob/master/marked.min.js) with 19.1 kb (says it's "Built for speed")
- [showdown](https://github.com/showdownjs/showdown/blob/master/dist/showdown.min.js) with 27.6 kb 

I haven't used them yet, so I can not comment on their performance or correctness. Hope that helps.

**Comment by beerendlauwers** [comment]
The recent commits add Markdown preview support.

**Comment by beerendlauwers** [comment]
Markdown preview button added to the file preview text area as well in 67734b86fae9a29df1df8fdc9160cd3bdb86d45c. I think this concludes your reqest?
