### ISSUE TITLE
Communicate at the beginning of a submission that markdown is used

### ISSUE THREAD

**Issue by m0rphism** [beerendlauwers/HaskAnything#30]
I just made my first submission and only found out indirectly that I can use markdown by stumbling over the pull request preview after I've already formatted my content in plain text. It might be helpful for new users to tell them right at the beginning of a submission, that all text fields can be laid out with markdown, to keep their spirit up :)

**Comment by beerendlauwers** [comment]
Even better, we use Pandoc, so you get awesome code styling as well :)

**Comment by beerendlauwers** [comment]
You can now include `$partial("ui/elements/markdown-support.html")$` to add a blurb about how the field supports Markdown. See the [presentation description field](http://haskanything.com/ui/submit/presentation.html), for example.
