### ISSUE TITLE
Webinterface: libraries are used as tags; tags are thrown away

### ISSUE THREAD

**Issue by m0rphism** [beerendlauwers/HaskAnything#35]
When adding a new presentation, the _tags_ and _libraries_ fields get mixed up. The content of the _libraries_ fields gets used for _tags_ and the content of _tags_ is not contained in the generated markdown at all.

This problem exists at least since 19 days ago, as it can be also observed in #28.

**Comment by m0rphism** [comment]
The issue appears to be not specific to presentations: same behavior when adding papers or snippets.

**Comment by beerendlauwers** [comment]
Ah, I see. The move from Chosen to Select2 means that the jQuery selector probably needs to updated. Thanks for the catch.

**Comment by beerendlauwers** [comment]
Fixed in a9f61d9.
